'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text = v => Array.isArray(v) ? v.join(', ') : String(v ?? '');
const audio = $('#audio');
let collection='netlabels', genre='', page=1, docs=[], queue=[], request=0, releaseRequest=0;
let currentTrack=null, history=[], scrubbing=false, catalogue=[], saved=new Map(), currentView='discover';
const trackRegistry = new Map();
const keyOf = t => JSON.stringify([t.id,t.file]);
const audioUrl = t => 'https://archive.org/download/'+encodeURIComponent(t.id)+'/'+t.file.split('/').map(encodeURIComponent).join('/');
const tagsOf = d => (Array.isArray(d.subject) ? d.subject : text(d.subject).split(/[;,]/)).map(s=>String(s).trim().toLowerCase().slice(0,200)).filter(Boolean).slice(0,50);
function toast(message){$('#message').textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#message').textContent='',6500)}
function view(name){currentView=name;for(const n of ['discover','saved','queue','about'])$('#'+n).hidden=n!==name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='queue')renderQueue();if(name==='saved')renderSaved()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
async function json(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('Request failed');return await r.json()}finally{clearTimeout(timer)}}
const catalogueReady=json('catalogue.json?v=artwork-1').then(data=>{if(!Array.isArray(data.releases))throw Error('Invalid catalogue');catalogue=data.releases;$('#catalogueNote').textContent=`${catalogue.length} releases · up to two sample tracks per release · checked ${new Date(data.checkedAt).toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}`}).catch(()=>{catalogue=[];$('#catalogueNote').textContent='The starter shelf could not load. Reload or try Search the Archive.'});

// Device-local library. Every visible saved state follows a completed transaction.
const dbReady=new Promise((resolve,reject)=>{
 if(!window.indexedDB)return reject(Error('Storage unavailable'));
 const req=indexedDB.open('slop-library',1);
 req.onupgradeneeded=()=>req.result.createObjectStore('saved',{keyPath:'key'});
 req.onsuccess=()=>{req.result.onversionchange=()=>req.result.close();resolve(req.result)};
 req.onerror=()=>reject(req.error);req.onblocked=()=>toast('Close other Slop tabs, then reload to open your saved music.');
});
async function refreshSaved(){const db=await dbReady;const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readonly'),req=tx.objectStore('saved').getAll();tx.oncomplete=()=>resolve(req.result);tx.onerror=tx.onabort=()=>reject(tx.error)});saved=new Map(rows.map(r=>[r.key,r]));syncSaves();if(currentView==='saved')renderSaved()}
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('slop-library'):null;
channel?.addEventListener('message',()=>refreshSaved().catch(()=>storageError()));
function storageError(){ $('#saveState').textContent='Device storage is unavailable. Existing backup files remain safe.';toast('Could not save on this device. Allow browser storage and reload.'); }
const libraryReady=refreshSaved().then(()=>{$('#saveState').textContent=''}).catch(storageError);
async function toggleSave(t){await libraryReady;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved'),req=store.get(keyOf(t));req.onsuccess=()=>{if(req.result)store.delete(keyOf(t));else store.put({...portableTrack(t),key:keyOf(t),savedAt:new Date().toISOString()})};tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');toast(saved.has(keyOf(t))?'Saved on this device.':'Removed from Saved.')}catch{storageError()}}
function portableTrack(t){const label=s=>String(s||'').replace(/[\u0000-\u001f]/g,' ').slice(0,1000);return {id:t.id,file:t.file,title:label(t.title),artist:label(t.artist),release:label(t.release),tags:Array.isArray(t.tags)?t.tags.slice(0,50).map(s=>String(s).slice(0,200)):[]}}
function saveButton(t){const key=keyOf(t);trackRegistry.set(key,t);const on=saved.has(key);return `<button class="saveTrack${on?' is-saved':''}" data-save="${esc(key)}" aria-pressed="${on}" aria-label="${on?'Unsave':'Save'} ${esc(t.title)}">${on?'♥':'♡'}</button>`}
function syncSaves(){ $('#savedCount').textContent=saved.size;document.querySelectorAll('[data-save]').forEach(b=>{const on=saved.has(b.dataset.save),t=trackRegistry.get(b.dataset.save);b.textContent=on?'♥':'♡';b.classList.toggle('is-saved',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',(on?'Unsave ':'Save ')+(t?.title||'track'))});$('#saveCurrent').disabled=!currentTrack;$('#saveCurrent').textContent=currentTrack&&saved.has(keyOf(currentTrack))?'♥':'♡';$('#saveCurrent').setAttribute('aria-pressed',String(!!currentTrack&&saved.has(keyOf(currentTrack))));$('#saveCurrent').setAttribute('aria-label',(currentTrack&&saved.has(keyOf(currentTrack))?'Unsave ':'Save ')+(currentTrack?.title||'current track'))}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-save]');if(!b)return;const t=trackRegistry.get(b.dataset.save);if(t){b.disabled=true;await toggleSave(t);if(b.isConnected)b.disabled=false}});
$('#saveCurrent').onclick=()=>currentTrack&&toggleSave(currentTrack);
function trackRow(t,i,kind){trackRegistry.set(keyOf(t),t);return `<div class="track"><button data-${kind}play="${i}" aria-label="Play ${esc(t.title)}">▶</button><span>${esc(t.title)}<br><small class="dim">${esc(t.artist)}</small></span>${saveButton(t)}<button data-${kind}next="${i}" aria-label="Play ${esc(t.title)} next">Play next</button>${kind==='q'?`<button data-remove="${i}" aria-label="Remove ${esc(t.title)} from queue">Remove</button>`:''}</div>`}
function bindTracks(tracks,kind,root){root.querySelectorAll(`[data-${kind}play]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'play']);const t=kind==='q'?queue.splice(i,1)[0]:tracks[i];renderQueue();play(t)});root.querySelectorAll(`[data-${kind}next]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'next']);const t=kind==='q'?queue.splice(i,1)[0]:tracks[i];queue.unshift(t);renderQueue();toast('Will play next: '+t.title)});}
function renderSaved(){const tracks=[...saved.values()].sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''));$('#savedList').innerHTML=tracks.length?tracks.map((t,i)=>trackRow(t,i,'s')+`<div class="savedLinks"><button data-similar="${i}">More like this</button><a href="https://archive.org/details/${encodeURIComponent(t.id)}" target="_blank" rel="noopener">Original release</a></div>`).join(''):'<div class="notice"><h2>No saved tracks yet.</h2><button id="savedBrowse">Browse the starter shelf</button></div>';$('#savedBrowse')?.addEventListener('click',()=>view('discover'));$('#exportLibrary').disabled=!tracks.length;bindTracks(tracks,'s',$('#savedList'));$('#savedList').querySelectorAll('[data-similar]').forEach(b=>b.onclick=()=>{const t=tracks[Number(b.dataset.similar)];related({identifier:t.id,creator:t.artist,title:t.title,subject:t.tags})})}
$('#exportLibrary').onclick=async()=>{try{await refreshSaved();const payload={format:'slop-saved-tracks',version:1,exportedAt:new Date().toISOString(),tracks:[...saved.values()].map(portableTrack)},backup=JSON.stringify(payload,null,2)+'\n';$('#backupText').value=backup;$('#downloadBackup').href='data:application/json;charset=utf-8,'+encodeURIComponent(backup);$('#downloadBackup').download='slop-saved-'+new Date().toISOString().slice(0,10)+'.json';$('#exportCount').textContent=payload.tracks.length+' saved tracks. Keep this file somewhere safe.';$('#exportDialog').showModal()}catch{storageError()}};
$('#closeExport').onclick=()=>$('#exportDialog').close();
$('#importLibrary').onclick=()=>$('#importFile').click();
function validateImport(data){if(!data||data.format!=='slop-saved-tracks'||data.version!==1||!Array.isArray(data.tracks)||data.tracks.length>10000)throw Error('Choose a Slop saved-tracks backup (version 1).');return data.tracks.map(t=>{if(!t||typeof t!=='object')throw Error('The backup contains an invalid track.');for(const f of ['id','file','title','artist','release'])if(typeof t[f]!=='string'||t[f].length>(f==='file'?1500:1000)||(/[\u0000-\u001f]/.test(t[f])))throw Error('The backup contains an invalid track.');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,199}$/.test(t.id)||!t.file||t.file.startsWith('/')||t.file.includes('\\')||t.file.split('/').some(x=>x==='..'||x==='.')||! /\.(mp3|ogg|m4a)$/i.test(t.file))throw Error('The backup contains an invalid Archive reference.');if(!Array.isArray(t.tags)||t.tags.length>50||t.tags.some(x=>typeof x!=='string'||x.length>200))throw Error('The backup contains invalid tags.');return portableTrack(t)})}
let pendingImport=null;
$('#importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('This backup is too large (maximum 10 MB).');const tracks=validateImport(JSON.parse(await file.text()));pendingImport=[...new Map(tracks.map(t=>[keyOf(t),t])).values()];await refreshSaved();const count=pendingImport.filter(t=>!saved.has(keyOf(t))).length;$('#importSummary').textContent=`${count} new saved ${count===1?'track':'tracks'} will be added. ${pendingImport.length-count} already saved. Your existing saved tracks will stay as they are.`;$('#confirmImport').disabled=!count;$('#importDialog').showModal()}catch(e){pendingImport=null;toast(e instanceof SyntaxError?'This file is not a readable JSON backup.':e.message)}};
$('#cancelImport').onclick=()=>{$('#importDialog').close();pendingImport=null};
$('#confirmImport').onclick=async()=>{if(!pendingImport)return;$('#confirmImport').disabled=true;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved');for(const t of pendingImport){const key=keyOf(t),req=store.get(key);req.onsuccess=()=>{if(!req.result)store.put({...t,key,savedAt:new Date().toISOString()})}}tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');pendingImport=null;$('#importDialog').close();view('saved');toast('Backup imported. Your saved tracks are ready.')}catch{storageError();$('#confirmImport').disabled=false}};

async function search(append=false){const seq=++request;$('#relatedNote').hidden=true;$('#resetShelf').hidden=true;if(!append){page=1;docs=[];$('#results').replaceChildren()}$('#more').hidden=true;$('#status').textContent='Loading the shelf…';const local=$('#shelfMode').value==='starter';$('#sort').hidden=local;$('#collections').hidden=local;const query=$('#query').value.trim();
 if(local){await catalogueReady;if(seq!==request)return;const words=query.toLowerCase().split(/\s+/).filter(Boolean);docs=catalogue.filter(d=>(!genre||tagsOf(d).includes(genre))&&words.every(w=>[text(d.title),text(d.creator),text(d.subject),...d.tracks.map(t=>t.title)].join(' ').toLowerCase().includes(w)));renderCards();$('#resultCount').textContent=docs.length+' RELEASES';$('#shelfTitle').textContent=genre?genre[0].toUpperCase()+genre.slice(1)+' in the pile':'A pile of slop';$('#status').textContent=docs.length?'':catalogue.length?'No matches here. Try another sound or Search the Archive.':'The starter shelf could not load. Try reloading.';return}
 $('#status').textContent='Looking through the Archive…';let q=`collection:${collection} AND (mediatype:audio OR mediatype:etree)`;if(query)q+=' AND ('+query.replace(/[+\-!(){}\[\]^"~*?:\\/]|&&|\|\|/g,' ')+')';if(genre)q+=' AND subject:"'+genre+'"';const p=new URLSearchParams({q,rows:'20',page:String(page),output:'json'});for(const f of ['identifier','title','creator','subject','date','licenseurl'])p.append('fl[]',f);p.append('sort[]',$('#sort').value);
 try{const data=await json('https://archive.org/advancedsearch.php?'+p);if(seq!==request)return;if(!data.response)throw Error('No response');docs.push(...data.response.docs);renderCards();$('#resultCount').textContent=data.response.numFound.toLocaleString()+' RELEASES';$('#status').textContent=docs.length?'':'No releases found. Try another sound or search.';$('#more').hidden=docs.length>=data.response.numFound;$('#shelfTitle').textContent=genre?genre[0].toUpperCase()+genre.slice(1)+' trails':collection==='etree'?'From the Live Music Archive':collection==='clinicalarchives'?'From Clinical Archives':'Across the Archive'}catch{if(seq!==request)return;$('#status').textContent='The Archive couldn’t be reached. The starter shelf is still available.';if(append)page=Math.max(1,page-1);else $('#results').innerHTML='<div class="notice"><h2>The wider shelf is out of reach.</h2><button id="retry">Try again</button> <button id="useStarter">Back to the starter shelf</button></div>';$('#retry')?.addEventListener('click',()=>search());$('#useStarter')?.addEventListener('click',()=>{$('#shelfMode').value='starter';search()})}}
function renderCards(){SlopArtwork.resetLazy();$('#results').innerHTML=docs.map((d,i)=>`<article class="card"><button class="cover" data-open="${i}" aria-label="Open ${esc(text(d.title))}"><img loading="lazy" src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Cover for ${esc(text(d.title))}"></button><h3>${esc(text(d.title)||d.identifier)}</h3><p>${esc(text(d.creator)||'Artist not listed')}</p><div class="meta">${esc(/^0|^$/.test(text(d.date))?'UNDATED':text(d.date).slice(0,4))} · ${d.tracks?'STARTER SHELF':'ARCHIVE RELEASE'}</div><div class="cardTags">${esc((d.why||tagsOf(d).slice(0,3)).join(' · '))}</div><button class="relatedButton" data-related="${i}">More like this</button></article>`).join('');$('#results').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRelease(docs[Number(b.dataset.open)]));$('#results').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>related(docs[Number(b.dataset.related)]));$('#results').querySelectorAll('.cover img').forEach((im,i)=>SlopArtwork.attach(im,docs[i].identifier,docs[i].coverFiles,true))}
async function related(seed){const seq=++request;await catalogueReady;if(seq!==request)return;view('discover');$('#shelfMode').value='starter';$('#sort').hidden=true;$('#collections').hidden=true;$('#more').hidden=true;const known=catalogue.find(d=>d.identifier===seed.identifier),tags=tagsOf(known||seed);const pool=catalogue.filter(d=>d.identifier!==seed.identifier).map(d=>({...d,why:tagsOf(d).filter(t=>tags.some(s=>s===t||s.includes(t))),random:Math.random()})).filter(d=>d.why.length).sort((a,b)=>b.why.length-a.why.length||a.random-b.random);docs=[];while(pool.length&&docs.length<12){let i=pool.findIndex(d=>text(d.creator)!==text(docs.at(-1)?.creator));if(i<0)i=0;docs.push(pool.splice(i,1)[0])}$('#shelfTitle').textContent='More like '+text(seed.title);$('#resultCount').textContent=docs.length+' RELEASES';$('#status').textContent=docs.length?'':'No tag matches on this small shelf yet. Try another release.';$('#relatedNote').hidden=false;$('#relatedNote').textContent='Matched by shared tags: '+(tags.join(', ')||'none supplied')+'. Each result shows its matching tags.';$('#resetShelf').hidden=false;$('#release').close();renderCards();window.scrollTo({top:0,behavior:'smooth'})}
$('#resetShelf').onclick=()=>{genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!b.dataset.genre));search()};
$('#search').onsubmit=e=>{e.preventDefault();search()};$('#sort').onchange=()=>search();$('#shelfMode').onchange=()=>search();$('#more').onclick=()=>{page++;search(true)};
document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{genre=b.dataset.genre;document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',x===b));search()});
document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{collection=b.dataset.collection;genre='';$('#shelfMode').value='archive';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',!x.dataset.genre));search();window.scrollTo({top:0,behavior:'smooth'})});
$('#close').onclick=()=>{releaseRequest++;$('#release').close()};
async function openRelease(d){const seq=++releaseRequest;$('#releaseBody').innerHTML='<p role="status">Opening the release…</p>';if(!$('#release').open)$('#release').showModal();try{let md=d,tracks;if(d.tracks){tracks=d.tracks.map(t=>({...t,id:d.identifier,release:text(d.title),tags:tagsOf(d)}))}else{const m=await json('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(seq!==releaseRequest)return;md=m.metadata||{};let files=(m.files||[]).filter(f=>!f.private&&/\.(mp3|ogg|m4a)$/i.test(f.name));const mp3=files.filter(f=>/\.mp3$/i.test(f.name));if(mp3.length)files=mp3;files.sort((a,b)=>(parseInt(a.track)||0)-(parseInt(b.track)||0)||a.name.localeCompare(b.name,undefined,{numeric:true}));tracks=files.map(f=>({title:text(f.title)||f.name.replace(/\.[^.]+$/,''),artist:text(f.creator||md.creator)||'Artist not listed',file:f.name,id:d.identifier,release:text(md.title)||d.identifier,tags:tagsOf(md)}))}
 if(seq!==releaseRequest)return;$('#releaseBody').innerHTML=`<div class="detailtop"><img src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Release artwork"><div><div class="eyebrow">${esc(text(md.date).slice(0,4))} · ${tracks.length} ${d.tracks?'SAMPLE TRACKS':'TRACKS'}</div><h2>${esc(text(md.title)||d.identifier)}</h2><p class="dim">${esc(text(md.creator)||'Artist not listed')}</p><a target="_blank" rel="noopener" href="https://archive.org/details/${encodeURIComponent(d.identifier)}">Full release & rights</a></div></div><p class="dim">${esc(tagsOf(md).join(' · '))}</p><button id="releaseRelated">More like this</button><div class="tracks">${tracks.length?tracks.map((t,i)=>trackRow(t,i,'r')).join(''):'<p>No browser-playable tracks were found. Try the original release.</p>'}</div>`;bindTracks(tracks,'r',$('#releaseBody'));$('#releaseRelated').onclick=()=>related(d);SlopArtwork.attach($('#releaseBody img'),d.identifier,d.coverFiles);
 }catch{if(seq===releaseRequest)$('#releaseBody').innerHTML='<h2>This release couldn’t be loaded.</h2><p>Try again later or <a target="_blank" rel="noopener" href="https://archive.org/details/'+encodeURIComponent(d.identifier)+'">open the original release</a>.</p>'}}
let playRequest=0;
async function play(t,remember=true){if(!t)return;const seq=++playRequest;if(remember&&currentTrack)history.push(currentTrack);currentTrack=t;$('#previous').disabled=!history.length;$('#togglePlay').disabled=false;$('#seek').disabled=true;$('#seek').value=0;$('#seek').style.setProperty('--progress','0%');$('#elapsed').textContent='0:00';$('#duration').textContent='0:00';$('#nowCover').hidden=false;$('#nowCover').src='https://archive.org/services/img/'+encodeURIComponent(t.id);SlopArtwork.attach($('#nowCover'),t.id,catalogue.find(d=>d.identifier===t.id)?.coverFiles);$('#nowTitle').textContent=t.title;$('#nowArtist').textContent=t.artist+(t.release?' · '+t.release:'');audio.src=audioUrl(t);syncSaves();try{await audio.play()}catch(e){if(seq===playRequest&&e.name!=='AbortError')$('#nowArtist').textContent='Press play to listen, or try another track.'}return {title:t.title,artist:t.artist}}
audio.onerror=()=>$('#nowArtist').textContent='This audio couldn’t be reached. Try another track.';
function renderQueue(){$('#qcount').textContent=queue.length;$('#playerQcount').textContent=queue.length;$('#queueList').innerHTML=queue.length?queue.map((t,i)=>trackRow(t,i,'q')).join(''):'<div class="notice"><h2>Nothing in the trough yet.</h2><button id="back">Browse releases</button></div>';$('#back')?.addEventListener('click',()=>view('discover'));bindTracks(queue,'q',$('#queueList'));$('#queueList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{queue.splice(Number(b.dataset.remove),1);renderQueue()});$('#next').disabled=!queue.length}
function next(){if(queue.length){const t=queue.shift();renderQueue();play(t)}}$('#next').onclick=next;audio.onended=next;renderQueue();search();

const seek=$('#seek'),fmt=t=>{t=Number.isFinite(t)?Math.max(0,t):0;return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')};
function updateSeek(){const dur=audio.duration,valid=Number.isFinite(dur)&&dur>0;seek.disabled=!valid;if(valid){seek.max=dur;$('#duration').textContent=fmt(dur);if(!scrubbing){seek.value=audio.currentTime;$('#elapsed').textContent=fmt(audio.currentTime)}seek.style.setProperty('--progress',(Number(seek.value)/dur*100)+'%');let buffer=0;for(let i=0;i<audio.buffered.length;i++)if(audio.buffered.start(i)<=audio.currentTime)buffer=audio.buffered.end(i);seek.style.setProperty('--buffer',(buffer/dur*100)+'%');seek.setAttribute('aria-valuetext',fmt(Number(seek.value))+' of '+fmt(dur))}}
for(const event of ['timeupdate','durationchange','loadedmetadata','progress','seeked'])audio.addEventListener(event,updateSeek);
seek.addEventListener('input',()=>{scrubbing=true;$('#elapsed').textContent=fmt(Number(seek.value));$('#seekPreview').textContent=fmt(Number(seek.value));$('#seekPreview').hidden=false;updateSeek()});
seek.addEventListener('change',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value);scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});seek.addEventListener('blur',()=>{scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});
$('#togglePlay').onclick=async()=>{if(audio.paused){try{await audio.play()}catch(e){$('#nowArtist').textContent='Playback couldn’t start. Try another track.'}}else audio.pause()};
function syncPlay(){const paused=audio.paused;$('#togglePlay').textContent=paused?'▶':'Ⅱ';$('#togglePlay').setAttribute('aria-label',paused?'Play':'Pause')}
audio.addEventListener('play',syncPlay);audio.addEventListener('pause',syncPlay);audio.addEventListener('ended',syncPlay);
$('#previous').onclick=()=>{if(audio.currentTime>3){audio.currentTime=0;return}if(history.length){if(currentTrack)queue.unshift(currentTrack);const t=history.pop();renderQueue();play(t,false)}};
$('#volume').oninput=()=>{audio.volume=Number($('#volume').value);audio.muted=audio.volume===0;syncMute()};function syncMute(){$('#mute').textContent=audio.muted?'Muted':'Sound';$('#mute').setAttribute('aria-label',audio.muted?'Unmute':'Mute');$('#mute').setAttribute('aria-pressed',String(audio.muted))}$('#mute').onclick=()=>{audio.muted=!audio.muted;syncMute()};
$('#queueToggle').onclick=()=>{view('queue');window.scrollTo({top:0,behavior:'smooth'})};


if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_archive_music',description:'Search the Archive and update the visible discovery shelf.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},execute:async input=>{if(!input||typeof input.query!=='string'||input.query.length>200)throw Error('Invalid search');$('#shelfMode').value='archive';$('#query').value=input.query;view('discover');await search();return {releases:docs.map(d=>({identifier:d.identifier,title:text(d.title)})),status:$('#status').textContent}}})).catch(()=>{})}catch{}}
