'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text = v => Array.isArray(v) ? v.join(', ') : String(v ?? '');
const controlIcons={"play":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m8 5 11 7-11 7Z\"/></svg>","pause":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 5v14M16 5v14\"/></svg>","previous":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 5v14m14-14L8 12l11 7Z\"/></svg>","next":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 5v14M5 5l11 7-11 7Z\"/></svg>","sound":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9h4l5-4v14l-5-4H3Z\"/><path d=\"M16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14\"/></svg>","muted":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9h4l5-4v14l-5-4H3Z\"/><path d=\"m16 9 6 6m0-6-6 6\"/></svg>","queue":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 6h18M3 12h12M3 18h12m4-6 4 3-4 3Z\"/></svg>"};
const audio = $('#audio');
let collection='', genre='', page=1, docs=[], queue=[], albumQueue=[], request=0, releaseRequest=0;
let currentTrack=null, history=[], scrubbing=false, saved=new Map(), currentView='discover';
const trackRegistry = new Map();
const keyOf = t => JSON.stringify([t.id,t.file]);
const audioUrl = t => 'https://archive.org/download/'+encodeURIComponent(t.id)+'/'+t.file.split('/').map(encodeURIComponent).join('/');
const tagsOf = d => (Array.isArray(d.subject) ? d.subject : text(d.subject).split(/[;,]/)).map(s=>String(s).trim().toLowerCase().slice(0,200)).filter(Boolean).slice(0,50);
function toast(message){$('#message').textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#message').textContent='',6500)}
function view(name){currentView=name;for(const n of ['discover','saved','queue','about'])$('#'+n).hidden=n!==name;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='queue')renderQueue();if(name==='saved')renderSaved()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
async function json(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('Request failed');return await r.json()}finally{clearTimeout(timer)}}

// Device-local library. Every visible saved state follows a completed transaction.
const dbReady=new Promise((resolve,reject)=>{
 if(!window.indexedDB)return reject(Error('Storage unavailable'));
 const req=indexedDB.open('slop-library',1);
 req.onupgradeneeded=()=>req.result.createObjectStore('saved',{keyPath:'key'});
 req.onsuccess=()=>{req.result.onversionchange=()=>req.result.close();resolve(req.result)};
 req.onerror=()=>reject(req.error);req.onblocked=()=>toast('Close other Slop tabs, then reload to open your saved music.');
});
async function refreshSaved(){const db=await dbReady;const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readonly'),req=tx.objectStore('saved').getAll();tx.oncomplete=()=>resolve(req.result);tx.onerror=tx.onabort=()=>reject(tx.error)});saved=new Map(rows.map(r=>[r.key,r]));syncSaves();if(currentView==='saved')renderSaved()}
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('slop-library'):null;
channel?.addEventListener('message',()=>refreshSaved().catch(()=>storageError()));
function storageError(){ $('#saveState').textContent='Device storage is unavailable. Existing backup files remain safe.';toast('Could not save on this device. Allow browser storage and reload.'); }
const libraryReady=refreshSaved().then(()=>{$('#saveState').textContent=''}).catch(storageError);
async function toggleSave(t){await libraryReady;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved'),req=store.get(keyOf(t));req.onsuccess=()=>{if(req.result)store.delete(keyOf(t));else store.put({...portableTrack(t),key:keyOf(t),savedAt:new Date().toISOString()})};tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');toast(saved.has(keyOf(t))?'Saved on this device.':'Removed from Saved.')}catch{storageError()}}
function portableTrack(t){const label=s=>String(s||'').replace(/[\u0000-\u001f]/g,' ').slice(0,1000);return {id:t.id,file:t.file,title:label(t.title),artist:label(t.artist),release:label(t.release),tags:Array.isArray(t.tags)?t.tags.slice(0,50).map(s=>String(s).slice(0,200)):[]}}
function saveButton(t){const key=keyOf(t);trackRegistry.set(key,t);const on=saved.has(key);return `<button class="saveTrack${on?' is-saved':''}" data-save="${esc(key)}" aria-pressed="${on}" aria-label="${on?'Unsave':'Save'} ${esc(t.title)}">${on?'♥':'♡'}</button>`}
function syncSaves(){ $('#savedCount').textContent=saved.size;document.querySelectorAll('[data-save]').forEach(b=>{const on=saved.has(b.dataset.save),t=trackRegistry.get(b.dataset.save);b.textContent=on?'♥':'♡';b.classList.toggle('is-saved',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',(on?'Unsave ':'Save ')+(t?.title||'track'))});$('#saveCurrent').disabled=!currentTrack;$('#saveCurrent').textContent=currentTrack&&saved.has(keyOf(currentTrack))?'♥':'♡';$('#saveCurrent').setAttribute('aria-pressed',String(!!currentTrack&&saved.has(keyOf(currentTrack))));$('#saveCurrent').setAttribute('aria-label',(currentTrack&&saved.has(keyOf(currentTrack))?'Unsave ':'Save ')+(currentTrack?.title||'current track'))}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-save]');if(!b)return;const t=trackRegistry.get(b.dataset.save);if(t){b.disabled=true;await toggleSave(t);if(b.isConnected)b.disabled=false}});
$('#saveCurrent').onclick=()=>currentTrack&&toggleSave(currentTrack);
function trackRow(t,i,kind){trackRegistry.set(keyOf(t),t);return `<div class="track"><button data-${kind}play="${i}" aria-label="Play ${esc(t.title)}">${controlIcons.play}</button><span>${esc(t.title)}<br><small class="dim">${esc(t.artist)}</small></span>${saveButton(t)}<button data-${kind}next="${i}" title="Play next" aria-label="Play ${esc(t.title)} next">${controlIcons.queue}</button>${(kind==='q'||kind==='a')?`<button data-remove="${i}" data-queue-kind="${kind}" aria-label="Remove ${esc(t.title)} from queue">Remove</button>`:''}</div>`}
function bindTracks(tracks,kind,root){root.querySelectorAll(`[data-${kind}play]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'play']);let t;if(kind==='q')t=queue.splice(i,1)[0];else if(kind==='a'){t=albumQueue[i];albumQueue.splice(0,i+1)}else{t=tracks[i];if(kind==='r')albumQueue=tracks.slice(i+1)}renderQueue();play(t)});root.querySelectorAll(`[data-${kind}next]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'next']);const t=kind==='q'?queue.splice(i,1)[0]:tracks[i];albumQueue=albumQueue.filter(x=>keyOf(x)!==keyOf(t));queue.unshift(t);renderQueue();toast('Will play next: '+t.title)});}
function renderSaved(){const tracks=[...saved.values()].sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''));$('#savedList').innerHTML=tracks.length?tracks.map((t,i)=>trackRow(t,i,'s')+`<div class="savedLinks"><button data-similar="${i}">More like this</button><a href="https://archive.org/details/${encodeURIComponent(t.id)}" target="_blank" rel="noopener">Original release</a></div>`).join(''):'<div class="notice"><h2>No saved tracks yet.</h2><button id="savedBrowse">Browse music</button></div>';$('#savedBrowse')?.addEventListener('click',()=>view('discover'));$('#exportLibrary').disabled=!tracks.length;bindTracks(tracks,'s',$('#savedList'));$('#savedList').querySelectorAll('[data-similar]').forEach(b=>b.onclick=()=>{const t=tracks[Number(b.dataset.similar)];related({identifier:t.id,creator:t.artist,title:t.title,subject:t.tags})})}
$('#exportLibrary').onclick=async()=>{try{await refreshSaved();const payload={format:'slop-saved-tracks',version:1,exportedAt:new Date().toISOString(),tracks:[...saved.values()].map(portableTrack)},backup=JSON.stringify(payload,null,2)+'\n';$('#backupText').value=backup;$('#downloadBackup').href='data:application/json;charset=utf-8,'+encodeURIComponent(backup);$('#downloadBackup').download='slop-saved-'+new Date().toISOString().slice(0,10)+'.json';$('#exportCount').textContent=payload.tracks.length+' saved tracks. Keep this file somewhere safe.';$('#exportDialog').showModal()}catch{storageError()}};
$('#closeExport').onclick=()=>$('#exportDialog').close();
$('#importLibrary').onclick=()=>$('#importFile').click();
function validateImport(data){if(!data||data.format!=='slop-saved-tracks'||data.version!==1||!Array.isArray(data.tracks)||data.tracks.length>10000)throw Error('Choose a Slop saved-tracks backup (version 1).');return data.tracks.map(t=>{if(!t||typeof t!=='object')throw Error('The backup contains an invalid track.');for(const f of ['id','file','title','artist','release'])if(typeof t[f]!=='string'||t[f].length>(f==='file'?1500:1000)||(/[\u0000-\u001f]/.test(t[f])))throw Error('The backup contains an invalid track.');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,199}$/.test(t.id)||!t.file||t.file.startsWith('/')||t.file.includes('\\')||t.file.split('/').some(x=>x==='..'||x==='.')||! /\.(mp3|ogg|m4a)$/i.test(t.file))throw Error('The backup contains an invalid Archive reference.');if(!Array.isArray(t.tags)||t.tags.length>50||t.tags.some(x=>typeof x!=='string'||x.length>200))throw Error('The backup contains invalid tags.');return portableTrack(t)})}
let pendingImport=null;
$('#importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('This backup is too large (maximum 10 MB).');const tracks=validateImport(JSON.parse(await file.text()));pendingImport=[...new Map(tracks.map(t=>[keyOf(t),t])).values()];await refreshSaved();const count=pendingImport.filter(t=>!saved.has(keyOf(t))).length;$('#importSummary').textContent=`${count} new saved ${count===1?'track':'tracks'} will be added. ${pendingImport.length-count} already saved. Your existing saved tracks will stay as they are.`;$('#confirmImport').disabled=!count;$('#importDialog').showModal()}catch(e){pendingImport=null;toast(e instanceof SyntaxError?'This file is not a readable JSON backup.':e.message)}};
$('#cancelImport').onclick=()=>{$('#importDialog').close();pendingImport=null};
$('#confirmImport').onclick=async()=>{if(!pendingImport)return;$('#confirmImport').disabled=true;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved');for(const t of pendingImport){const key=keyOf(t),req=store.get(key);req.onsuccess=()=>{if(!req.result)store.put({...t,key,savedAt:new Date().toISOString()})}}tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');pendingImport=null;$('#importDialog').close();view('saved');toast('Backup imported. Your saved tracks are ready.')}catch{storageError();$('#confirmImport').disabled=false}};

let relatedSeed=null;
const quote=value=>'"'+String(value).replace(/["\\]/g,' ').slice(0,200)+'"';
async function search(append=false){const seq=++request;if(!append){page=1;docs=[];$('#results').replaceChildren()}$('#more').hidden=true;$('#status').textContent='Searching the Archive…';$('#resultCount').textContent='';document.querySelectorAll('[data-collection]').forEach(b=>b.classList.toggle('active',collection===b.dataset.collection));document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!relatedSeed&&!collection&&genre===b.dataset.genre));$('#sort').hidden=!!relatedSeed;$('#resetShelf').hidden=!(relatedSeed||collection);$('#relatedNote').hidden=!relatedSeed;
 let q='(mediatype:audio OR mediatype:etree)';
 if(collection)q+=' AND collection:'+quote(collection);
 const query=$('#query').value.trim().replace(/[+\-!(){}\[\]^"~*?:\\/]|&&|\|\|/g,' ').trim();if(query)q+=' AND ('+query+')';if(genre)q+=' AND subject:'+quote(genre);
 if(relatedSeed){const tags=tagsOf(relatedSeed).slice(0,6);if(!tags.length){$('#status').textContent='This release has no tags to match.';$('#resultCount').textContent='0 RELEASES';return}q+=' AND ('+tags.map(t=>'subject:'+quote(t)).join(' OR ')+') AND NOT identifier:'+quote(relatedSeed.identifier);$('#relatedNote').textContent='Shared tags: '+tags.join(' · ')}
 const p=new URLSearchParams({q,rows:'20',page:String(page),output:'json'});for(const f of ['identifier','title','creator','subject','date','licenseurl'])p.append('fl[]',f);p.append('sort[]',relatedSeed?'downloads desc':$('#sort').value);
 $('#shelfTitle').textContent=relatedSeed?'More like '+text(relatedSeed.title):genre?genre[0].toUpperCase()+genre.slice(1):collection==='etree'?'Live Music Archive':collection==='clinicalarchives'?'Clinical Archives':collection==='netlabels'?'Netlabels':'A pile of slop';
 try{const data=await json('https://archive.org/advancedsearch.php?'+p);if(seq!==request)return;if(!data.response)throw Error();docs.push(...data.response.docs.map(d=>relatedSeed?{...d,why:tagsOf(d).filter(t=>tagsOf(relatedSeed).some(s=>t.includes(s)||s.includes(t)))}:d));renderCards();$('#resultCount').textContent=data.response.numFound.toLocaleString()+' RELEASES';$('#status').textContent=docs.length?'':'No releases found. Try another search.';$('#more').hidden=docs.length>=data.response.numFound}catch{if(seq!==request)return;$('#status').textContent='The Archive could not be reached. Try again.';if(append){page=Math.max(1,page-1);$('#more').hidden=false}else $('#results').innerHTML='<button id="retry">Try again</button>';$('#retry')?.addEventListener('click',()=>search())}}
function renderCards(){SlopArtwork.resetLazy();$('#results').innerHTML=docs.map((d,i)=>`<article class="card"><button class="cover" data-open="${i}" aria-label="Open ${esc(text(d.title))}"><img loading="lazy" src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Cover for ${esc(text(d.title))}"></button><h3>${esc(text(d.title)||d.identifier)}</h3><p>${esc(text(d.creator)||'Artist not listed')}</p><div class="meta">${esc(/^0|^$/.test(text(d.date))?'UNDATED':text(d.date).slice(0,4))} · ARCHIVE RELEASE</div><div class="cardTags">${esc((d.why||tagsOf(d).slice(0,3)).join(' · '))}</div><button class="relatedButton" data-related="${i}">More like this</button></article>`).join('');$('#results').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRelease(docs[Number(b.dataset.open)]));$('#results').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>related(docs[Number(b.dataset.related)]));$('#results').querySelectorAll('.cover img').forEach((im,i)=>SlopArtwork.attach(im,docs[i].identifier,docs[i].coverFiles,true))}
async function related(seed){relatedSeed=seed;collection='';genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!b.dataset.genre));view('discover');$('#release').close();await search();window.scrollTo({top:0,behavior:'smooth'})}
$('#resetShelf').onclick=()=>{relatedSeed=null;collection='';genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!b.dataset.genre));search()};
$('#search').onsubmit=e=>{e.preventDefault();relatedSeed=null;collection='';search()};$('#sort').onchange=()=>search();$('#more').onclick=()=>{page++;search(true)};
document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{relatedSeed=null;collection="";genre=b.dataset.genre;document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',x===b));search()});
document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{relatedSeed=null;collection=b.dataset.collection;genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',!x.dataset.genre));search();window.scrollTo({top:0,behavior:'smooth'})});
$('#close').onclick=()=>{releaseRequest++;$('#release').close()};
async function openRelease(d){const seq=++releaseRequest;$('#releaseBody').innerHTML='<p role="status">Opening the release…</p>';if(!$('#release').open)$('#release').showModal();try{let md=d,tracks;if(d.fullTracks){tracks=d.tracks.map(t=>({...t,id:d.identifier,release:text(d.title),tags:tagsOf(d)}))}else{const m=await json('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(seq!==releaseRequest)return;md=m.metadata||{};let files=(m.files||[]).filter(f=>!f.private&&/\.(mp3|ogg|m4a)$/i.test(f.name));const mp3=files.filter(f=>/\.mp3$/i.test(f.name));if(mp3.length)files=mp3;files.sort((a,b)=>(parseInt(a.track)||0)-(parseInt(b.track)||0)||a.name.localeCompare(b.name,undefined,{numeric:true}));tracks=files.map(f=>({title:text(f.title)||f.name.replace(/\.[^.]+$/,''),artist:text(f.creator||md.creator)||'Artist not listed',file:f.name,id:d.identifier,release:text(md.title)||d.identifier,tags:tagsOf(md)}))}
 if(seq!==releaseRequest)return;$('#releaseBody').innerHTML=`<div class="detailtop"><img src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Release artwork"><div><div class="eyebrow">${esc(text(md.date).slice(0,4))} · ${tracks.length} TRACKS</div><h2>${esc(text(md.title)||d.identifier)}</h2><p class="dim">${esc(text(md.creator)||'Artist not listed')}</p><a target="_blank" rel="noopener" href="https://archive.org/details/${encodeURIComponent(d.identifier)}">Full release & rights</a></div></div><p class="dim">${esc(tagsOf(md).join(' · '))}</p><button id="releaseRelated">More like this</button><div class="tracks">${tracks.length?tracks.map((t,i)=>trackRow(t,i,'r')).join(''):'<p>No browser-playable tracks were found. Try the original release.</p>'}</div>`;bindTracks(tracks,'r',$('#releaseBody'));if(tracks.length){albumQueue=tracks.slice(1);renderQueue();play(tracks[0])}$('#releaseRelated').onclick=()=>related(d);SlopArtwork.attach($('#releaseBody img'),d.identifier,d.coverFiles);
 }catch{if(seq===releaseRequest)$('#releaseBody').innerHTML='<h2>This release couldn’t be loaded.</h2><p>Try again later or <a target="_blank" rel="noopener" href="https://archive.org/details/'+encodeURIComponent(d.identifier)+'">open the original release</a>.</p>'}}
let playRequest=0;
async function play(t,remember=true){if(!t)return;const seq=++playRequest;if(remember&&currentTrack)history.push(currentTrack);currentTrack=t;$('#previous').disabled=!history.length;$('#togglePlay').disabled=false;$('#seek').disabled=true;$('#seek').value=0;$('#seek').style.setProperty('--progress','0%');$('#elapsed').textContent='0:00';$('#duration').textContent='0:00';$('#nowCover').hidden=false;$('#nowCover').src='https://archive.org/services/img/'+encodeURIComponent(t.id);SlopArtwork.attach($('#nowCover'),t.id,undefined);$('#nowTitle').textContent=t.title;$('#nowArtist').textContent=t.artist+(t.release?' · '+t.release:'');audio.src=audioUrl(t);syncSaves();try{await audio.play()}catch(e){if(seq===playRequest&&e.name!=='AbortError')$('#nowArtist').textContent='Press play to listen, or try another track.'}return {title:t.title,artist:t.artist}}
audio.onerror=()=>$('#nowArtist').textContent='This audio couldn’t be reached. Try another track.';
function renderQueue(){const total=queue.length+albumQueue.length;$('#qcount').textContent=total;$('#playerQcount').textContent=total;$('#queueToggle').setAttribute('aria-label','Queue, '+total+' '+(total===1?'track':'tracks'));$('#queueList').innerHTML='<h2>Up next</h2>'+(queue.length?queue.map((t,i)=>trackRow(t,i,'q')).join(''):'<p class="dim">No added tracks.</p>')+'<h2>From this album</h2>'+(albumQueue.length?albumQueue.map((t,i)=>trackRow(t,i,'a')).join(''):'<p class="dim">No album queued.</p>');bindTracks(queue,'q',$('#queueList'));bindTracks(albumQueue,'a',$('#queueList'));$('#queueList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{(b.dataset.queueKind==='q'?queue:albumQueue).splice(Number(b.dataset.remove),1);renderQueue()});$('#next').disabled=!total}
function next(){const t=queue.length?queue.shift():albumQueue.shift();if(t){renderQueue();play(t)}}$('#next').onclick=next;audio.onended=next;renderQueue();search();

const seek=$('#seek'),fmt=t=>{t=Number.isFinite(t)?Math.max(0,t):0;return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')};
function updateSeek(){const dur=audio.duration,valid=Number.isFinite(dur)&&dur>0;seek.disabled=!valid;if(valid){seek.max=dur;$('#duration').textContent=fmt(dur);if(!scrubbing){seek.value=audio.currentTime;$('#elapsed').textContent=fmt(audio.currentTime)}seek.style.setProperty('--progress',(Number(seek.value)/dur*100)+'%');let buffer=0;for(let i=0;i<audio.buffered.length;i++)if(audio.buffered.start(i)<=audio.currentTime)buffer=audio.buffered.end(i);seek.style.setProperty('--buffer',(buffer/dur*100)+'%');seek.setAttribute('aria-valuetext',fmt(Number(seek.value))+' of '+fmt(dur))}}
for(const event of ['timeupdate','durationchange','loadedmetadata','progress','seeked'])audio.addEventListener(event,updateSeek);
seek.addEventListener('input',()=>{scrubbing=true;$('#elapsed').textContent=fmt(Number(seek.value));$('#seekPreview').textContent=fmt(Number(seek.value));$('#seekPreview').hidden=false;updateSeek()});
seek.addEventListener('change',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value);scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});seek.addEventListener('blur',()=>{scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});
$('#togglePlay').onclick=async()=>{if(audio.paused){try{await audio.play()}catch(e){$('#nowArtist').textContent='Playback couldn’t start. Try another track.'}}else audio.pause()};
function syncPlay(){const paused=audio.paused;$('#togglePlay').innerHTML=controlIcons[paused?'play':'pause'];$('#togglePlay').setAttribute('aria-label',paused?'Play':'Pause')}
audio.addEventListener('play',syncPlay);audio.addEventListener('pause',syncPlay);audio.addEventListener('ended',syncPlay);
$('#previous').onclick=()=>{if(audio.currentTime>3){audio.currentTime=0;return}if(history.length){if(currentTrack)queue.unshift(currentTrack);const t=history.pop();renderQueue();play(t,false)}};
$('#volume').oninput=()=>{audio.volume=Number($('#volume').value);audio.muted=audio.volume===0;syncMute()};function syncMute(){$('#mute').innerHTML=controlIcons[audio.muted?'muted':'sound'];$('#mute').title=audio.muted?'Unmute':'Mute';$('#mute').setAttribute('aria-label',audio.muted?'Unmute':'Mute');$('#mute').setAttribute('aria-pressed',String(audio.muted))}$('#mute').onclick=()=>{audio.muted=!audio.muted;syncMute()};
$('#queueToggle').onclick=()=>{view('queue');window.scrollTo({top:0,behavior:'smooth'})};


if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_archive_music',description:'Search the Archive and update the visible discovery shelf.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},execute:async input=>{if(!input||typeof input.query!=='string'||input.query.length>200)throw Error('Invalid search');relatedSeed=null;collection='';genre='';$('#query').value=input.query;view('discover');await search();return {releases:docs.map(d=>({identifier:d.identifier,title:text(d.title)})),status:$('#status').textContent}}})).catch(()=>{})}catch{}}
