'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text = v => Array.isArray(v) ? v.join(', ') : String(v ?? '');
const controlIcons={"play":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m8 5 11 7-11 7Z\"/></svg>","pause":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M8 5v14M16 5v14\"/></svg>","previous":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M5 5v14m14-14L8 12l11 7Z\"/></svg>","next":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M19 5v14M5 5l11 7-11 7Z\"/></svg>","sound":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9h4l5-4v14l-5-4H3Z\"/><path d=\"M16 8a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14\"/></svg>","muted":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 9h4l5-4v14l-5-4H3Z\"/><path d=\"m16 9 6 6m0-6-6 6\"/></svg>","queue":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M3 6h18M3 12h12M3 18h12m4-6 4 3-4 3Z\"/></svg>","heart":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8Z\"/></svg>","heartFilled":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"currentColor\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.9-8.6a5.5 5.5 0 0 0-.1-7.8Z\"/></svg>","remove":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\" class=\"controlIcon\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.8\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"m6 6 12 12M18 6 6 18\"/></svg>"};
const audio = $('#audio');
const PAGE_SIZE=30;
let collection='', genre='', page=1, totalResults=0, docs=[], queue=[], albumQueue=[], request=0, releaseRequest=0;
let currentTrack=null, history=[], scrubbing=false, saved=new Map(), currentView='discover';
const trackRegistry = new Map();
const keyOf = t => JSON.stringify([t.id,t.file]);
const audioUrl = t => 'https://archive.org/download/'+encodeURIComponent(t.id)+'/'+t.file.split('/').map(encodeURIComponent).join('/');
const tagsOf = d => (Array.isArray(d.subject) ? d.subject : text(d.subject).split(/[;,]/)).map(s=>String(s).trim().toLowerCase().slice(0,200)).filter(Boolean).slice(0,50);
function toast(message){$('#message').textContent=message;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#message').textContent='',6500)}
function setDiscoverMode(mode){const home=$('#discoverHome'),results=$('#searchResults');if(!home||!results)return;const homeMode=mode==='home';home.hidden=!homeMode;results.hidden=homeMode;}
function showSearchResults(){setDiscoverMode('results')}
function view(name){currentView=name;for(const n of ['discover','saved','queue','log','docs','about'])$('#'+n).hidden=n!==name;document.querySelectorAll('[data-view]').forEach(b=>{const active=b.dataset.view===name;b.classList.toggle('active',active);b.toggleAttribute('aria-current',active)});if(name==='queue')renderQueue();if(name==='saved')renderSaved()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view(b.dataset.view);if(b.dataset.view==='discover')setDiscoverMode('home')});
async function json(url){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok){const error=Error('Archive returned '+r.status);error.archiveStatus=r.status;throw error}return await r.json()}finally{clearTimeout(timer)}}
function archiveFailure(error){const status=Number(error?.archiveStatus);if(status>=500&&status<600)return 'Internet Archive is temporarily unavailable. Slop is working normally — try again in a few minutes.';if(error?.name==='AbortError')return 'Internet Archive is taking too long to respond. Slop is working normally — try again shortly.';return 'Slop can’t get a response from Internet Archive right now. The app is working normally — try again in a few minutes.'}

// Device-local likes. Every visible like state follows a completed transaction.
const dbReady=new Promise((resolve,reject)=>{
 if(!window.indexedDB)return reject(Error('Storage unavailable'));
 const req=indexedDB.open('slop-library',1);
 req.onupgradeneeded=()=>req.result.createObjectStore('saved',{keyPath:'key'});
 req.onsuccess=()=>{req.result.onversionchange=()=>req.result.close();resolve(req.result)};
 req.onerror=()=>reject(req.error);req.onblocked=()=>toast('Close other Slop tabs, then reload your liked tracks.');
});
async function refreshSaved(){const db=await dbReady;const rows=await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readonly'),req=tx.objectStore('saved').getAll();tx.oncomplete=()=>resolve(req.result);tx.onerror=tx.onabort=()=>reject(tx.error)});saved=new Map(rows.map(r=>[r.key,r]));syncSaves();if(currentView==='saved')renderSaved()}
const channel=typeof BroadcastChannel==='function'?new BroadcastChannel('slop-library'):null;
channel?.addEventListener('message',()=>refreshSaved().catch(()=>storageError()));
function storageError(){ $('#saveState').textContent='Device storage is unavailable. Existing files remain safe.';toast('Could not update your likes on this device. Allow browser storage and reload.'); }
const libraryReady=refreshSaved().then(()=>{$('#saveState').textContent=''}).catch(storageError);
async function toggleSave(t){await libraryReady;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved'),req=store.get(keyOf(t));req.onsuccess=()=>{if(req.result)store.delete(keyOf(t));else store.put({...portableTrack(t),key:keyOf(t),savedAt:new Date().toISOString()})};tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');toast(saved.has(keyOf(t))?'Liked on this device.':'Removed from Liked.')}catch{storageError()}}
function portableTrack(t){const label=s=>String(s||'').replace(/[\u0000-\u001f]/g,' ').slice(0,1000);return {id:t.id,file:t.file,title:label(t.title),artist:label(t.artist),release:label(t.release),tags:Array.isArray(t.tags)?t.tags.slice(0,50).map(s=>String(s).slice(0,200)):[]}}
function saveButton(t){const key=keyOf(t);trackRegistry.set(key,t);const on=saved.has(key);return `<button class="saveTrack${on?' is-saved':''}" data-save="${esc(key)}" aria-pressed="${on}" aria-label="${on?'Unlike':'Like'} ${esc(t.title)}">${controlIcons[on?'heartFilled':'heart']}</button>`}
function syncSaves(){document.querySelectorAll('[data-save]').forEach(b=>{const on=saved.has(b.dataset.save),t=trackRegistry.get(b.dataset.save);b.innerHTML=controlIcons[on?'heartFilled':'heart'];b.classList.toggle('is-saved',on);b.setAttribute('aria-pressed',String(on));b.setAttribute('aria-label',(on?'Unlike ':'Like ')+(t?.title||'track'))});$('#saveCurrent').disabled=!currentTrack;$('#saveCurrent').innerHTML=controlIcons[currentTrack&&saved.has(keyOf(currentTrack))?'heartFilled':'heart'];$('#saveCurrent').setAttribute('aria-pressed',String(!!currentTrack&&saved.has(keyOf(currentTrack))));$('#saveCurrent').setAttribute('aria-label',(currentTrack&&saved.has(keyOf(currentTrack))?'Unlike ':'Like ')+(currentTrack?.title||'current track'))}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-save]');if(!b)return;const t=trackRegistry.get(b.dataset.save);if(t){b.disabled=true;await toggleSave(t);if(b.isConnected)b.disabled=false}});
$('#saveCurrent').onclick=()=>currentTrack&&toggleSave(currentTrack);
function trackRow(t,i,kind){trackRegistry.set(keyOf(t),t);const remove=(kind==='q'||kind==='a')?`<button class="removeTrack" data-remove="${i}" data-queue-kind="${kind}" aria-label="Remove ${esc(t.title)} from queue">${controlIcons.remove}<span class="srOnly">Remove</span></button>`:'';return `<div class="track"><button class="trackPlay" data-${kind}play="${i}" aria-label="Play ${esc(t.title)}">${controlIcons.play}</button><span class="trackCopy">${esc(t.title)}<br><small class="dim">${esc(t.artist)}</small></span><div class="trackActions">${saveButton(t)}<button data-${kind}next="${i}" title="Play next" aria-label="Play ${esc(t.title)} next">${controlIcons.queue}</button>${remove}</div></div>`}
function bindTracks(tracks,kind,root){root.querySelectorAll(`[data-${kind}play]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'play']);let t;if(kind==='q')t=queue.splice(i,1)[0];else if(kind==='a'){t=albumQueue[i];albumQueue.splice(0,i+1)}else{t=tracks[i];if(kind==='r')albumQueue=tracks.slice(i+1)}renderQueue();play(t)});root.querySelectorAll(`[data-${kind}next]`).forEach(b=>b.onclick=()=>{const i=Number(b.dataset[kind+'next']);const t=kind==='q'?queue.splice(i,1)[0]:tracks[i];albumQueue=albumQueue.filter(x=>keyOf(x)!==keyOf(t));queue.unshift(t);renderQueue();toast('Will play next: '+t.title)});}
function renderSaved(){const tracks=[...saved.values()].sort((a,b)=>(b.savedAt||'').localeCompare(a.savedAt||''));$('#savedList').innerHTML=tracks.length?tracks.map((t,i)=>trackRow(t,i,'s')+`<div class="savedLinks"><button data-similar="${i}">More like this</button><a href="https://archive.org/details/${encodeURIComponent(t.id)}" target="_blank" rel="noopener">Original release</a></div>`).join(''):'<div class="notice"><h2>No liked tracks yet.</h2><button id="savedBrowse">Browse music</button></div>';$('#savedBrowse')?.addEventListener('click',()=>{view('discover');setDiscoverMode('home')});$('#exportLibrary').disabled=!tracks.length;bindTracks(tracks,'s',$('#savedList'));$('#savedList').querySelectorAll('[data-similar]').forEach(b=>b.onclick=()=>{const t=tracks[Number(b.dataset.similar)];related({identifier:t.id,creator:t.artist,title:t.title,subject:t.tags})})}
$('#exportLibrary').onclick=async()=>{try{await refreshSaved();const payload={format:'slop-saved-tracks',version:1,exportedAt:new Date().toISOString(),tracks:[...saved.values()].map(portableTrack)},backup=JSON.stringify(payload,null,2)+'\n';$('#backupText').value=backup;$('#downloadBackup').href='data:application/json;charset=utf-8,'+encodeURIComponent(backup);$('#downloadBackup').download='slop-liked-'+new Date().toISOString().slice(0,10)+'.json';$('#exportCount').textContent=payload.tracks.length+' liked '+(payload.tracks.length===1?'track':'tracks')+'. Save this file somewhere safe.';$('#exportDialog').showModal()}catch{storageError()}};
$('#closeExport').onclick=()=>$('#exportDialog').close();
$('#importLibrary').onclick=()=>$('#importFile').click();
function validateImport(data){if(!data||data.format!=='slop-saved-tracks'||data.version!==1||!Array.isArray(data.tracks)||data.tracks.length>10000)throw Error('Choose a Slop liked-tracks file (version 1).');return data.tracks.map(t=>{if(!t||typeof t!=='object')throw Error('The file contains an invalid track.');for(const f of ['id','file','title','artist','release'])if(typeof t[f]!=='string'||t[f].length>(f==='file'?1500:1000)||(/[\u0000-\u001f]/.test(t[f])))throw Error('The file contains an invalid track.');if(!/^[A-Za-z0-9][A-Za-z0-9_.-]{0,199}$/.test(t.id)||!t.file||t.file.startsWith('/')||t.file.includes('\\')||t.file.split('/').some(x=>x==='..'||x==='.')||!SlopSlipProtocol.PLAYABLE_FILE.test(t.file))throw Error('The file contains an invalid Archive reference.');if(!Array.isArray(t.tags)||t.tags.length>50||t.tags.some(x=>typeof x!=='string'||x.length>200))throw Error('The file contains invalid tags.');return portableTrack(t)})}
let pendingImport=null;
$('#importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>10*1024*1024)throw Error('This file is too large (maximum 10 MB).');const tracks=validateImport(JSON.parse(await file.text()));pendingImport=[...new Map(tracks.map(t=>[keyOf(t),t])).values()];await refreshSaved();const count=pendingImport.filter(t=>!saved.has(keyOf(t))).length;$('#importSummary').textContent=`${count} new liked ${count===1?'track':'tracks'} will be added. ${pendingImport.length-count} already liked. Your existing likes will stay as they are.`;$('#confirmImport').disabled=!count;$('#importDialog').showModal()}catch(e){pendingImport=null;toast(e instanceof SyntaxError?'This file is not readable JSON.':e.message)}};
$('#cancelImport').onclick=()=>{$('#importDialog').close();pendingImport=null};
$('#confirmImport').onclick=async()=>{if(!pendingImport)return;$('#confirmImport').disabled=true;try{const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('saved','readwrite'),store=tx.objectStore('saved');for(const t of pendingImport){const key=keyOf(t),req=store.get(key);req.onsuccess=()=>{if(!req.result)store.put({...t,key,savedAt:new Date().toISOString()})}}tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error)});await refreshSaved();channel?.postMessage('updated');pendingImport=null;$('#importDialog').close();view('saved');toast('Loaded. Your liked tracks are ready.')}catch{storageError();$('#confirmImport').disabled=false}};

let relatedSeed=null;
const quote=value=>'"'+String(value).replace(/["\\]/g,' ').slice(0,200)+'"';
function renderPager(){const pages=Math.ceil(totalResults/PAGE_SIZE),pager=$('#pager');pager.hidden=pages<=1;$('#pageNumber').textContent=String(page-1);$('#pagePrevious').disabled=page<=1;$('#pageNext').disabled=page>=pages}
async function search(targetPage=1){const nextPage=Math.max(1,Math.floor(Number(targetPage)||1)),seq=++request;docs=[];totalResults=0;$('#results').replaceChildren();$('#pager').hidden=true;$('#status').textContent='Searching the Archive…';$('#resultCount').textContent='';document.querySelectorAll('[data-collection]').forEach(b=>b.classList.toggle('active',collection===b.dataset.collection));document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!relatedSeed&&!collection&&genre===b.dataset.genre));$('#resetShelf').hidden=!(relatedSeed||collection);$('#relatedNote').hidden=!relatedSeed;
 let q='(mediatype:audio OR mediatype:etree)';
 if(collection)q+=' AND collection:'+quote(collection);
 const query=$('#query').value.trim().slice(0,200),scope=$('#searchScope').value;if(query)q+=' AND '+SlopArchive.searchClause(query,scope);if(genre)q+=' AND subject:'+quote(genre);
 if(relatedSeed){const tags=tagsOf(relatedSeed).slice(0,6);if(!tags.length){$('#status').textContent='This release has no tags to match.';$('#resultCount').textContent='0 RELEASES';return}q+=' AND ('+tags.map(t=>'subject:'+quote(t)).join(' OR ')+') AND NOT identifier:'+quote(relatedSeed.identifier);$('#relatedNote').textContent='Shared tags: '+tags.join(' · ')}
 const p=new URLSearchParams({q,rows:String(PAGE_SIZE),page:String(nextPage),output:'json'});for(const f of ['identifier','title','creator','subject','date','licenseurl'])p.append('fl[]',f);if(!query)p.append('sort[]',relatedSeed?'downloads desc':'publicdate desc');
 $('#shelfTitle').textContent=query?({all:'Search results',artist:'Releases by artist',release:'Release titles',tags:'Releases with this tag'}[scope]):relatedSeed?'More like '+text(relatedSeed.title):genre?genre[0].toUpperCase()+genre.slice(1):collection==='etree'?'Live Music Archive':collection==='clinicalarchives'?'Clinical Archives':collection==='netlabels'?'Netlabels':'A pile of slop';
 try{const data=await json('https://archive.org/advancedsearch.php?'+p);if(seq!==request)return;if(!data.response)throw Error();docs=data.response.docs.map(d=>relatedSeed?{...d,why:tagsOf(d).filter(t=>tagsOf(relatedSeed).some(s=>t.includes(s)||s.includes(t)))}:d);page=nextPage;totalResults=Number(data.response.numFound)||0;renderCards();renderDiscoverRecommendations();$('#resultCount').textContent=totalResults.toLocaleString()+' RELEASES';$('#status').textContent=docs.length?(query?({all:'Matching artist names and release titles · relevance first',artist:'Matching credited artists · relevance first',release:'Matching release titles · relevance first',tags:'Matching Archive tags · relevance first'}[scope]):''):'No releases found. Try another name or search type.';renderPager()}catch(error){if(seq!==request)return;$('#status').textContent=archiveFailure(error);$('#results').innerHTML='<button id="retry">Try again</button>';renderDiscoverRecommendations();$('#retry')?.addEventListener('click',()=>search(nextPage))}}
function renderCards(){SlopArtwork.resetLazy();$('#results').innerHTML=docs.map((d,i)=>`<article class="card"><button class="cover" data-play-album="${i}" aria-label="Play album ${esc(text(d.title))}"><img loading="lazy" src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Cover for ${esc(text(d.title))}"></button><h3><button class="releaseTitle" data-open="${i}" aria-label="Open release ${esc(text(d.title)||d.identifier)}">${esc(text(d.title)||d.identifier)}</button></h3><p>${esc(text(d.creator)||'Artist not listed')}</p><div class="meta">${esc(/^0|^$/.test(text(d.date))?'UNDATED':text(d.date).slice(0,4))} · ARCHIVE RELEASE</div><div class="cardTags">${esc((d.why||tagsOf(d).slice(0,3)).join(' · '))}</div><button class="relatedButton" data-related="${i}">More like this</button></article>`).join('');$('#results').querySelectorAll('[data-play-album]').forEach(b=>b.onclick=()=>openRelease(docs[Number(b.dataset.playAlbum)],true));$('#results').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRelease(docs[Number(b.dataset.open)]));$('#results').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>related(docs[Number(b.dataset.related)]));$('#results').querySelectorAll('.cover img').forEach((im,i)=>SlopArtwork.attach(im,docs[i].identifier,docs[i].coverFiles,true))}
function renderDiscoverRecommendations(){const root=$('#clapResults');if(!root)return;const picks=docs.slice(0,3);if(!picks.length){root.innerHTML='<p class="dim">No live recommendations yet. Try an Archive search instead.</p>';return}root.innerHTML=picks.map((d,i)=>{const title=text(d.title)||d.identifier,artist=text(d.creator)||'Artist not listed',year=/^0|^$/.test(text(d.date))?'Undated':text(d.date).slice(0,4);return '<article class="clapCard"><button class="clapCover" data-discover-play="'+i+'" aria-label="Play '+esc(title)+'"><img loading="lazy" src="https://archive.org/services/img/'+encodeURIComponent(d.identifier)+'" alt="Cover for '+esc(title)+'"></button><div class="clapCopy"><p class="cardKicker">'+esc(year)+' · Archive release</p><h3><button class="releaseTitle" data-discover-open="'+i+'" aria-label="Open release '+esc(title)+'">'+esc(title)+'</button></h3><p>'+esc(artist)+'</p><button class="relatedButton" data-discover-open="'+i+'">Open release</button></div></article>'}).join('');root.querySelectorAll('[data-discover-play]').forEach(b=>b.onclick=()=>openRelease(picks[Number(b.dataset.discoverPlay)],true));root.querySelectorAll('[data-discover-open]').forEach(b=>b.onclick=()=>openRelease(picks[Number(b.dataset.discoverOpen)]));root.querySelectorAll('.clapCover img').forEach((im,i)=>SlopArtwork.attach(im,picks[i].identifier,picks[i].coverFiles,true))}
async function related(seed){relatedSeed=seed;collection='';genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!b.dataset.genre));view('discover');showSearchResults();$('#release').close();await search();window.scrollTo({top:0,behavior:'smooth'})}
$('#resetShelf').onclick=()=>{relatedSeed=null;collection='';genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(b=>b.classList.toggle('active',!b.dataset.genre));showSearchResults();search()};
$('#browseGenres').onclick=()=>{relatedSeed=null;collection='';genre='';$('#query').value='';showSearchResults();search()};
$('#search').onsubmit=e=>{e.preventDefault();relatedSeed=null;collection='';genre='';showSearchResults();search()};$('#pagePrevious').onclick=()=>{if(page>1){showSearchResults();search(page-1);window.scrollTo({top:0,behavior:'smooth'})}};$('#pageNext').onclick=()=>{if(page<Math.ceil(totalResults/PAGE_SIZE)){showSearchResults();search(page+1);window.scrollTo({top:0,behavior:'smooth'})}};
document.querySelectorAll('[data-genre]').forEach(b=>b.onclick=()=>{relatedSeed=null;collection="";genre=b.dataset.genre;document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',x===b));showSearchResults();search()});
document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{relatedSeed=null;collection=b.dataset.collection;genre='';$('#query').value='';document.querySelectorAll('[data-genre]').forEach(x=>x.classList.toggle('active',!x.dataset.genre));showSearchResults();search();window.scrollTo({top:0,behavior:'smooth'})});

$('#searchScope').onchange=()=>{const scope=$('#searchScope').value;$('#query').placeholder={all:'Artist or release name…',artist:'Artist or band name…',release:'Release title…',tags:'Ambient, tape music, field recordings…'}[scope];if($('#query').value.trim())$('#search').requestSubmit()};
$('#navSearch').onclick=()=>{view('discover');showSearchResults();$('#query').focus();window.scrollTo({top:0,behavior:'smooth'})};
$('#navGenres').onclick=()=>{view('discover');setDiscoverMode('home');$('#genre-title').scrollIntoView({block:'center',behavior:'smooth'})};
$('#close').onclick=()=>{releaseRequest++;$('#release').close()};
async function openRelease(d,autoplay=false){const seq=++releaseRequest;if(!autoplay){$('#releaseBody').innerHTML='<p role="status">Opening the release…</p>';if(!$('#release').open)$('#release').showModal();}try{let md=d,tracks;if(d.fullTracks){tracks=d.tracks.map(t=>({...t,id:d.identifier,release:text(d.title),tags:tagsOf(d)}))}else{const m=await json('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(seq!==releaseRequest)return;md=m.metadata||{};const mime={mp3:'audio/mpeg',ogg:'audio/ogg',m4a:'audio/mp4',flac:'audio/flac',wav:'audio/wav',opus:'audio/ogg; codecs=opus'};const files=SlopSlipProtocol.selectArchiveFiles(m.files,ext=>!!audio.canPlayType(mime[ext]));tracks=files.map(f=>({title:text(f.title)||f.name.replace(/\.[^.]+$/,''),artist:text(f.creator||md.creator)||'Artist not listed',file:f.name,id:d.identifier,release:text(md.title)||d.identifier,tags:tagsOf(md)}))}
 if(seq!==releaseRequest)return;if(autoplay){if(tracks.length){albumQueue=tracks.slice(1);renderQueue();play(tracks[0])}else{toast('This item has no audio files your browser can play. Opening its details.');await openRelease(d,false)}return}$('#releaseBody').innerHTML=`<div class="detailtop"><img src="https://archive.org/services/img/${encodeURIComponent(d.identifier)}" alt="Release artwork"><div><div class="eyebrow">${esc(text(md.date).slice(0,4))} · ${tracks.length} TRACKS</div><h2>${esc(text(md.title)||d.identifier)}</h2><p class="dim">${esc(text(md.creator)||'Artist not listed')}</p><a target="_blank" rel="noopener" href="https://archive.org/details/${encodeURIComponent(d.identifier)}">Full release & rights</a></div></div><p class="dim">${esc(tagsOf(md).join(' · '))}</p><button id="releaseRelated">More like this</button><div class="tracks">${tracks.length?tracks.map((t,i)=>trackRow(t,i,'r')).join(''):'<p>This Archive item has no public audio files this browser can play. It may contain a download bundle or restricted files. Use Full release &amp; rights to check the original item.</p>'}</div>`;bindTracks(tracks,'r',$('#releaseBody'));$('#releaseRelated').onclick=()=>related(d);SlopArtwork.attach($('#releaseBody img'),d.identifier,d.coverFiles);
 }catch(error){const message=archiveFailure(error);if(seq===releaseRequest&&autoplay){toast(message);return}if(seq===releaseRequest)$('#releaseBody').innerHTML='<h2>This release couldn’t be loaded.</h2><p>'+esc(message)+' You can also <a target="_blank" rel="noopener" href="https://archive.org/details/'+encodeURIComponent(d.identifier)+'">open the original release</a>.</p>'}}
let playRequest=0;
async function play(t,remember=true,autoplay=true){
 if(!t)return;
 const seq=++playRequest,coverUrl='https://archive.org/services/img/'+encodeURIComponent(t.id),nowArtist=t.artist+(t.release?' · '+t.release:'');
 if(remember&&currentTrack)history.push(currentTrack);
 currentTrack=t;
 $('#previous').disabled=!history.length;
 $('#togglePlay').disabled=false;
 $('#seek').disabled=true;
 $('#seek').value=0;
 $('#seek').style.setProperty('--progress','0%');
 $('#elapsed').textContent='0:00';
 $('#duration').textContent='0:00';
 $('#nowCover').hidden=false;
 $('#nowCover').src=coverUrl;
 SlopArtwork.attach($('#nowCover'),t.id,undefined);
 $('#nowTitle').textContent=t.title;
 $('#nowArtist').textContent=nowArtist;
 $('#sidebarNow').hidden=false;
 $('#sidebarNowCover').src=coverUrl;
 SlopArtwork.attach($('#sidebarNowCover'),t.id,undefined);
 $('#sidebarNowCover').alt='Artwork for '+(t.release||t.title);
 audio.src=audioUrl(t);
 syncSaves();
 document.dispatchEvent(new Event('slop:trackchange'));
 if(!autoplay)return {title:t.title,artist:t.artist};
 try{await audio.play()}catch(e){if(seq===playRequest&&e.name!=='AbortError')$('#nowArtist').textContent='Press play to listen, or try another track.'}
 return {title:t.title,artist:t.artist}
}
audio.onerror=()=>$('#nowArtist').textContent='This audio couldn’t be reached. Try another track.';
function renderQueue(){const total=queue.length+albumQueue.length;$('#queueToggle').setAttribute('aria-label','Queue, '+total+' '+(total===1?'track':'tracks'));$('#queueList').innerHTML='<h2>Up next</h2>'+(queue.length?queue.map((t,i)=>trackRow(t,i,'q')).join(''):'<p class="dim">No added tracks.</p>')+'<h2>From this album</h2>'+(albumQueue.length?albumQueue.map((t,i)=>trackRow(t,i,'a')).join(''):'<p class="dim">No album queued.</p>');bindTracks(queue,'q',$('#queueList'));bindTracks(albumQueue,'a',$('#queueList'));$('#queueList').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{(b.dataset.queueKind==='q'?queue:albumQueue).splice(Number(b.dataset.remove),1);renderQueue()});$('#next').disabled=!total}
function next(){const t=queue.length?queue.shift():albumQueue.shift();if(t){renderQueue();play(t)}}$('#next').onclick=next;audio.onended=next;renderQueue();search();

const seek=$('#seek'),fmt=t=>{t=Number.isFinite(t)?Math.max(0,t):0;return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')};
function updateSeek(){const dur=audio.duration,valid=Number.isFinite(dur)&&dur>0;seek.disabled=!valid;if(valid){seek.max=dur;$('#duration').textContent=fmt(dur);if(!scrubbing){seek.value=audio.currentTime;$('#elapsed').textContent=fmt(audio.currentTime)}seek.style.setProperty('--progress',(Number(seek.value)/dur*100)+'%');let buffer=0;for(let i=0;i<audio.buffered.length;i++)if(audio.buffered.start(i)<=audio.currentTime)buffer=audio.buffered.end(i);seek.style.setProperty('--buffer',(buffer/dur*100)+'%');seek.setAttribute('aria-valuetext',fmt(Number(seek.value))+' of '+fmt(dur))}}
for(const event of ['timeupdate','durationchange','loadedmetadata','progress','seeked'])audio.addEventListener(event,updateSeek);
seek.addEventListener('input',()=>{scrubbing=true;$('#elapsed').textContent=fmt(Number(seek.value));$('#seekPreview').textContent=fmt(Number(seek.value));$('#seekPreview').hidden=false;updateSeek()});
seek.addEventListener('change',()=>{if(Number.isFinite(audio.duration))audio.currentTime=Number(seek.value);scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});seek.addEventListener('blur',()=>{scrubbing=false;$('#seekPreview').hidden=true;updateSeek()});
$('#togglePlay').onclick=async()=>{if(audio.paused){try{await audio.play()}catch(e){$('#nowArtist').textContent='Playback couldn’t start. Try another track.'}}else audio.pause()};
function syncPlay(){const paused=audio.paused;$('#togglePlay').innerHTML=controlIcons[paused?'play':'pause'];$('#togglePlay').setAttribute('aria-label',paused?'Play':'Pause')}
audio.addEventListener('play',syncPlay);audio.addEventListener('pause',syncPlay);audio.addEventListener('ended',syncPlay);
$('#previous').onclick=()=>{if(audio.currentTime>3){audio.currentTime=0;return}if(history.length){if(currentTrack)queue.unshift(currentTrack);const t=history.pop();renderQueue();play(t,false)}};
$('#volume').oninput=()=>{audio.volume=Number($('#volume').value);audio.muted=audio.volume===0;syncMute()};function syncMute(){$('#mute').innerHTML=controlIcons[audio.muted?'muted':'sound'];$('#mute').title=audio.muted?'Unmute':'Mute';$('#mute').setAttribute('aria-label',audio.muted?'Unmute':'Mute');$('#mute').setAttribute('aria-pressed',String(audio.muted))}$('#mute').onclick=()=>{audio.muted=!audio.muted;syncMute()};
$('#queueToggle').onclick=()=>{view('queue');window.scrollTo({top:0,behavior:'smooth'})};


if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'search_archive_music',description:'Search the Archive and update the visible discovery shelf.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},execute:async input=>{if(!input||typeof input.query!=='string'||input.query.length>200)throw Error('Invalid search');relatedSeed=null;collection='';genre='';$('#query').value=input.query;view('discover');showSearchResults();await search();return {releases:docs.map(d=>({identifier:d.identifier,title:text(d.title)})),status:$('#status').textContent}}})).catch(()=>{})}catch{}}

window.SlopSlipUI?.install({
 getCurrentTrack:()=>currentTrack,
 getPosition:()=>audio.currentTime,
 audio,
 toast,
 prepareTrack:t=>play(t,false,false),
 openRelease,
 onTrackChange:callback=>document.addEventListener('slop:trackchange',callback)
});

const navigationToggle=$('#navigationToggle'),navigationRail=navigationToggle.closest('aside');
function closeNavigation(){navigationRail.classList.remove('navigationOpen');navigationToggle.setAttribute('aria-expanded','false');navigationToggle.textContent='Menu'}
navigationToggle.onclick=()=>{const open=navigationRail.classList.toggle('navigationOpen');navigationToggle.setAttribute('aria-expanded',String(open));navigationToggle.textContent=open?'Close menu':'Menu'};
$('#slopNavigation').addEventListener('click',e=>{if(e.target.closest('button')){closeNavigation();if(matchMedia('(max-width:720px)').matches&&e.target.closest('button').id!=='navSearch')navigationToggle.focus()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navigationRail.classList.contains('navigationOpen')){closeNavigation();navigationToggle.focus()}});