'use strict';
// The existing likes and these records commit in the same IndexedDB database.
let personalState=SlopPersonal.empty();
async function readPersonal(){const db=await dbReady;const state=await new Promise((resolve,reject)=>{const tx=db.transaction('personal','readonly'),r=tx.objectStore('personal').get('state');tx.oncomplete=()=>resolve(r.result||SlopPersonal.empty());tx.onerror=tx.onabort=()=>reject(tx.error)});personalState=SlopPersonal.personal(state);window.slopPersonalState=personalState;renderPersonal();window.dispatchEvent(new Event('slop:personalchange'));return personalState;}
async function changePersonal(change){const db=await dbReady;await new Promise((resolve,reject)=>{const tx=db.transaction('personal','readwrite'),store=tx.objectStore('personal'),r=store.get('state');r.onsuccess=()=>{try{const state=SlopPersonal.personal(r.result||SlopPersonal.empty());change(state);store.put(SlopPersonal.personal(state),'state')}catch(e){tx.abort();reject(e)}};tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error||Error('The library could not be updated.'))});await readPersonal();channel?.postMessage('personal');}
const personalReady=readPersonal().catch(e=>toast('Personal library unavailable: '+e.message));
window.slopPersonalReady=personalReady;
channel?.addEventListener('message',e=>{if(e.data==='personal')readPersonal().catch(storageError)});
const personalId=()=>crypto.randomUUID();
function renderPersonal(){
 $('#excludeCreators').value=personalState.excludedCreators.join('\n');$('#diversify').checked=personalState.diversify;
 const select=$('#playlistSelect'),selected=select.value;select.innerHTML=personalState.playlists.map(p=>`<option value="${esc(p.id)}">${esc(p.title)}</option>`).join('');if(personalState.playlists.some(p=>p.id===selected))select.value=selected;
 renderPlaylist();$('#savedModes').innerHTML=personalState.modes.map(m=>`<div class="personalRow"><button data-mode="${esc(m.id)}">${esc(m.title)}</button><button data-delete-mode="${esc(m.id)}" aria-label="Delete mode ${esc(m.title)}">Remove</button></div>`).join('')||'<p class="dim">No saved discovery modes yet.</p>';
 $('#savedModes').querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{const m=personalState.modes.find(x=>x.id===b.dataset.mode);await changePersonal(s=>s.diversify=m.diversify);$('#query').value=m.query;$('#searchScope').value=m.scope;view('discover');$('#search').requestSubmit()});
 $('#savedModes').querySelectorAll('[data-delete-mode]').forEach(b=>b.onclick=()=>runPersonal(()=>changePersonal(s=>s.modes=s.modes.filter(m=>m.id!==b.dataset.deleteMode))));
 $('#exportLibrary').disabled=false;
}
async function runPersonal(action){try{await action()}catch(e){toast(e.message||'Could not save the change.')}}
$('#personalFilters').onsubmit=e=>{e.preventDefault();runPersonal(async()=>{const names=$('#excludeCreators').value.split('\n').map(x=>x.trim()).filter(Boolean),diversify=$('#diversify').checked;await changePersonal(s=>{s.excludedCreators=names;s.diversify=diversify});await search();toast('Discovery preferences saved on this device.')})};
$('#saveModeForm').onsubmit=e=>{e.preventDefault();const title=$('#modeTitle').value.trim();if(!title)return;runPersonal(async()=>{await changePersonal(s=>s.modes.push({id:personalId(),title,query:$('#query').value.trim(),scope:$('#searchScope').value,diversify:s.diversify}));$('#modeTitle').value='';toast('Discovery mode saved.')})};
$('#newPlaylistForm').onsubmit=e=>{e.preventDefault();const title=$('#playlistTitle').value.trim();if(!title)return;runPersonal(async()=>{const id=personalId();await changePersonal(s=>s.playlists.push({id,title,tracks:[]}));$('#playlistSelect').value=id;$('#playlistTitle').value='';renderPlaylist()})};
$('#playlistSelect').onchange=renderPlaylist;
function chosenPlaylist(){return personalState.playlists.find(p=>p.id===$('#playlistSelect').value)}
function renderPlaylist(){const p=chosenPlaylist();$('#playlistActions').hidden=!p;$('#playlistTracks').innerHTML=p?p.tracks.map((t,i)=>`<div class="personalTrack"><button data-personal-play="${i}">${esc(t.title)}<small>${esc(t.artist)}</small></button><button data-move="${i}" data-step="-1" ${i===0?'disabled':''} aria-label="Move ${esc(t.title)} up">↑</button><button data-move="${i}" data-step="1" ${i===p.tracks.length-1?'disabled':''} aria-label="Move ${esc(t.title)} down">↓</button><button data-personal-remove="${i}" aria-label="Remove ${esc(t.title)}">Remove</button></div>`).join(''):'<p class="dim">Create a playlist to keep a sequence of tracks.</p>';if(p)$('#renamePlaylist').value=p.title;
 $('#playlistTracks').querySelectorAll('[data-personal-play]').forEach(b=>b.onclick=()=>{const i=+b.dataset.personalPlay;albumQueue=p.tracks.slice(i+1);renderQueue();play(p.tracks[i])});
 $('#playlistTracks').querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>runPersonal(()=>changePersonal(s=>{const tracks=s.playlists.find(x=>x.id===p.id).tracks,i=+b.dataset.move,j=i+(+b.dataset.step);[tracks[i],tracks[j]]=[tracks[j],tracks[i]]})));
 $('#playlistTracks').querySelectorAll('[data-personal-remove]').forEach(b=>b.onclick=()=>runPersonal(()=>changePersonal(s=>s.playlists.find(x=>x.id===p.id).tracks.splice(+b.dataset.personalRemove,1))));
}
$('#addPlaylistTracks').onclick=()=>runPersonal(async()=>{const p=chosenPlaylist();if(!p)return;await refreshSaved();const source=$('#playlistSource').value,tracks=source==='current'?(currentTrack?[currentTrack]:[]):source==='queue'?[...queue,...albumQueue]:[...saved.values()];if(!tracks.length)return toast('No tracks in that selection.');await changePersonal(s=>s.playlists.find(x=>x.id===p.id).tracks.push(...tracks.map(portableTrack)));toast('Added '+tracks.length+' tracks. Repeated entries are kept.');});
$('#renamePlaylistButton').onclick=()=>runPersonal(()=>{const p=chosenPlaylist(),title=$('#renamePlaylist').value.trim();if(p&&title)return changePersonal(s=>s.playlists.find(x=>x.id===p.id).title=title)});
let removedPlaylist=null;
$('#deletePlaylist').onclick=()=>runPersonal(async()=>{const p=chosenPlaylist();if(!p)return;await changePersonal(s=>s.playlists=s.playlists.filter(x=>x.id!==p.id));removedPlaylist=p;$('#undoPlaylist').hidden=false;});
$('#undoPlaylist').onclick=()=>runPersonal(async()=>{if(removedPlaylist)await changePersonal(s=>s.playlists.push(removedPlaylist));removedPlaylist=null;$('#undoPlaylist').hidden=true});
$('#queuePlaylist').onclick=()=>{const p=chosenPlaylist();if(p){queue.push(...p.tracks.map(portableTrack));renderQueue();toast('Playlist added to Up next.')}};

// A complete snapshot reads both stores in a single transaction.
$('#exportLibrary').onclick=()=>runPersonal(async()=>{const db=await dbReady;const payload=await new Promise((resolve,reject)=>{const tx=db.transaction(['saved','personal'],'readonly'),likes=tx.objectStore('saved').getAll(),state=tx.objectStore('personal').get('state');tx.oncomplete=()=>resolve({format:'slop-library',version:2,exportedAt:new Date().toISOString(),tracks:likes.result.map(portableTrack),personal:SlopPersonal.personal(state.result||SlopPersonal.empty())});tx.onerror=tx.onabort=()=>reject(tx.error)});$('#backupText').value=JSON.stringify(payload,null,2)+'\n';$('#downloadBackup').href='data:application/json;charset=utf-8,'+encodeURIComponent($('#backupText').value);$('#downloadBackup').download='slop-library-'+new Date().toISOString().slice(0,10)+'.json';$('#exportCount').textContent=payload.tracks.length+' likes, '+payload.personal.playlists.length+' playlists, '+payload.personal.modes.length+' modes, and your exclusions. Audio and queue history are not included.';$('#exportDialog').showModal()});
let personalImport=null;
$('#importFile').onchange=e=>runPersonal(async()=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>10*1024*1024)throw Error('Maximum backup size is 10 MB.');personalImport=SlopPersonal.backup(JSON.parse(await file.text()));await refreshSaved();await readPersonal();const incoming=personalImport;$('#importSummary').textContent=`${incoming.tracks.length} liked tracks, ${incoming.personal.playlists.length} playlists and ${incoming.personal.modes.length} modes in this file. Existing likes stay. New exclusions are added. Conflicting playlists or modes are kept as separate imported copies; current preferences stay. Unavailable recordings keep their references.`;$('#confirmImport').disabled=false;$('#importDialog').showModal()});
$('#cancelImport').onclick=()=>{personalImport=null;$('#importDialog').close()};
$('#confirmImport').onclick=()=>runPersonal(async()=>{if(!personalImport)return;$('#confirmImport').disabled=true;const incoming=personalImport,db=await dbReady;try{await new Promise((resolve,reject)=>{const tx=db.transaction(['saved','personal'],'readwrite'),likes=tx.objectStore('saved'),state=tx.objectStore('personal'),r=state.get('state');r.onsuccess=()=>{try{state.put(r.result?SlopPersonal.merge(r.result,incoming.personal,personalId):incoming.personal,'state')}catch(e){tx.abort();reject(e)}};for(const t of incoming.tracks){const key=keyOf(t),read=likes.get(key);read.onsuccess=()=>{if(!read.result)likes.put({...t,key,savedAt:new Date().toISOString()})}}tx.oncomplete=resolve;tx.onerror=tx.onabort=()=>reject(tx.error||Error('Import failed; no changes committed.'))});await refreshSaved();await readPersonal();channel?.postMessage('updated');channel?.postMessage('personal');personalImport=null;$('#importDialog').close();view('saved');toast('Library loaded.')}finally{$('#confirmImport').disabled=false}});

// Queue recovery is opt-in: a paused snapshot, never automatic listening.
const sessionKey='slop-session-v1';let recoveryEnabled=false,lastSnapshot=0,recoveryErrorShown=false;
function saveSession(){if(!recoveryEnabled)return;try{if(queue.length+albumQueue.length>10000)throw Error('Queue recovery is limited to 10,000 tracks.');localStorage.setItem(sessionKey,JSON.stringify({version:1,current:currentTrack?portableTrack(currentTrack):null,queue:queue.map(portableTrack),album:albumQueue.map(portableTrack),position:Number.isFinite(audio.currentTime)?audio.currentTime:0}));lastSnapshot=Date.now();recoveryErrorShown=false}catch{try{localStorage.removeItem(sessionKey)}catch{}if(!recoveryErrorShown)toast('Queue recovery could not be saved. The queue may exceed this device’s storage or the 10,000-track limit.');recoveryErrorShown=true}}
try{recoveryEnabled=localStorage.getItem('slop-recover-queue')==='true'}catch{}
$('#recoverQueue').checked=recoveryEnabled;
$('#recoverQueue').onchange=()=>{recoveryEnabled=$('#recoverQueue').checked;try{localStorage.setItem('slop-recover-queue',String(recoveryEnabled));if(!recoveryEnabled)localStorage.removeItem(sessionKey);else saveSession()}catch{toast('Queue recovery storage is unavailable.')}};
if(recoveryEnabled&&!SlopSlipProtocol.looksLikeSlip(location.hash)){try{const snapshot=JSON.parse(localStorage.getItem(sessionKey)||'null');if(snapshot?.version===1&&Array.isArray(snapshot.queue)&&Array.isArray(snapshot.album)&&snapshot.queue.length+snapshot.album.length<=10000){const restoredQueue=snapshot.queue.map(SlopPersonal.track),restoredAlbum=snapshot.album.map(SlopPersonal.track),current=snapshot.current?SlopPersonal.track(snapshot.current):null;queue=restoredQueue;albumQueue=restoredAlbum;renderQueue();if(current){play(current,false,false);const source=audio.src,position=Number(snapshot.position)||0;audio.addEventListener('loadedmetadata',()=>{if(audio.src===source&&Number.isFinite(audio.duration))audio.currentTime=Math.min(Math.max(position,0),audio.duration)},{once:true})}}}catch{toast('The previous queue could not be restored. Your library is safe.')}}
document.addEventListener('slop:queuechange',saveSession);document.addEventListener('slop:trackchange',saveSession);
audio.addEventListener('pause',saveSession);audio.addEventListener('seeked',saveSession);audio.addEventListener('timeupdate',()=>{if(Date.now()-lastSnapshot>10000)saveSession()});window.addEventListener('pagehide',saveSession);
if('mediaSession' in navigator){document.addEventListener('slop:trackchange',()=>{if(currentTrack)navigator.mediaSession.metadata=new MediaMetadata({title:currentTrack.title,artist:currentTrack.artist,album:currentTrack.release})});for(const [action,handler] of Object.entries({play:()=>audio.play().catch(()=>toast('Press play to listen.')),pause:()=>audio.pause(),nexttrack:next,previoustrack:()=>$('#previous').click()})){try{navigator.mediaSession.setActionHandler(action,handler)}catch{}}}
