const {chromium}=require(process.env.SLOP_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
const base=process.env.SLOP_TEST_URL||'http://127.0.0.1:8766/tools/slop/';
const track={id:'unavailable-example',file:'song.flac',title:'A preserved reference',artist:'Example artist',release:'Example release',tags:['ambient']};
async function context(browser){const c=await browser.newContext({viewport:{width:1366,height:768}});await c.route('https://archive.org/**',route=>route.fulfill({contentType:'application/json',body:JSON.stringify({response:{numFound:3,docs:[{identifier:'one',title:'One',creator:'Excluded',subject:['ambient']},{identifier:'two',title:'Two',creator:'Other',subject:['ambient']},{identifier:'three',title:'Three',creator:'Other',subject:['ambient']}]}})}));return c;}
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.SLOP_BROWSER_CHANNEL?{channel:process.env.SLOP_BROWSER_CHANNEL}:{})});try{
 const c=await context(browser),page=await c.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 // Seed the shipping v1 database, then load the new app to exercise migration.
 await page.goto(new URL('LICENSE.txt',base).href);
 await page.evaluate(async t=>{await new Promise((resolve,reject)=>{const r=indexedDB.open('slop-library',1);r.onupgradeneeded=()=>r.result.createObjectStore('saved',{keyPath:'key'});r.onsuccess=()=>{const db=r.result,tx=db.transaction('saved','readwrite');tx.objectStore('saved').put({...t,key:JSON.stringify([t.id,t.file])});tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)}})},track);
 await page.goto(base);await page.locator('nav [data-view="saved"]').click();await page.waitForSelector('#savedList [data-splay]');
 await page.locator('#playlistTitle').fill('Repeat on purpose');await page.locator('#newPlaylistForm button').click();await page.waitForSelector('#playlistSelect option',{state:'attached'});
 await page.locator('#playlistSource').selectOption('liked');await page.locator('#addPlaylistTracks').click();await page.waitForSelector('#playlistTracks [data-personal-play]');await page.locator('#addPlaylistTracks').click();await page.waitForFunction(()=>document.querySelectorAll('[data-personal-play]').length===2);
 await page.locator('nav [data-view="discover"]').click();await page.locator('.personalPanel summary').click();await page.locator('#excludeCreators').fill('Excluded');await page.locator('#diversify').uncheck();await page.locator('#personalFilters button').click();
 await page.waitForFunction(()=>window.slopPersonalState?.excludedCreators.includes('excluded'));
 await page.locator('#query').fill('ambient');await page.locator('#searchScope').selectOption('tags');await page.locator('#search button').click();await page.waitForSelector('#results .card');assert.equal(await page.locator('#results .card').count(),2);
 await page.locator('#modeTitle').fill('Ambient without exclusions in the request');await page.locator('#saveModeForm button').click();await page.waitForSelector('[data-mode]');
 await page.locator('nav [data-view="saved"]').click();await page.locator('#exportLibrary').click();await page.waitForSelector('#exportDialog[open]');const data=JSON.parse(await page.locator('#backupText').inputValue());assert.equal(data.personal.playlists[0].tracks.length,2);assert.equal(data.personal.diversify,false);assert.equal(data.tracks.length,1);await page.locator('#closeExport').click();
 // Restore into a completely fresh browser context: no accounts, no source reads.
 const fresh=await context(browser),restored=await fresh.newPage();await restored.goto(base);await restored.locator('nav [data-view="saved"]').click();await restored.locator('#importFile').setInputFiles({name:'library.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});await restored.locator('#confirmImport').click();await restored.waitForSelector('#playlistTracks [data-personal-play]');assert.equal(await restored.locator('#playlistTracks [data-personal-play]').count(),2);assert.equal(await restored.locator('#savedList [data-splay]').count(),1);assert.equal(await restored.locator('#diversify').isChecked(),false);
 await restored.locator('#queuePlaylist').click();await restored.locator('nav [data-view="queue"]').click();await restored.locator('#recoverQueue').check();await restored.reload();await restored.locator('nav [data-view="queue"]').click();assert.equal(await restored.locator('#queueList [data-qplay]').count(),2);assert.equal(await restored.locator('#audio').evaluate(a=>a.paused),true);
 await restored.locator('nav [data-view="saved"]').click();if(process.env.SLOP_SCREENSHOTS)await restored.screenshot({path:process.env.SLOP_SCREENSHOTS+'/library-desktop.png'});
 for(const size of [[1366,768],[390,844]]){await restored.setViewportSize({width:size[0],height:size[1]});assert.equal(await restored.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
 if(process.env.SLOP_SCREENSHOTS)await restored.screenshot({path:process.env.SLOP_SCREENSHOTS+'/library-mobile.png'});assert.deepEqual(errors,[]);console.log('PASS: migration, repeated playlist entries, local exclusions, saved mode, full recovery, paused queue and responsive layout');
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
